### ISSUE TITLE
0.4.0 release checklist

### ISSUE THREAD

**Issue by mdickinson** [mdickinson/bigfloat#88]
- [x] Update acknowledgements for 3rd party contributors (done in #93)
- [x] Backport any changes on master that should go into 0.4.0. (#94)
- [x] Bump version number on release branch. (see #95)
- [x] Build sdist
- [x] Run `twine check` on sdist
- [x] Install from sdist locally, and check all tests pass
- [x] Tag the release, using an annotated tag
- [x] Upload to PyPI
- [x] Test again with a `pip install`ed version
- [x] Edit release page on GitHub

**Comment by mdickinson** [comment]
All done. Closing.
